FROM ubuntu:20.04
MAINTAINER HLXEasy <hlxeasy@gmail.com>

# Build parameters
ARG USERNAME="staker"
ARG GROUPNAME="staker"
ARG PASSWORD="staker123"
ARG UID="1000"
ARG GID="1000"

# Setup staker account
# Create working directory
# Change user UID and GID
RUN groupadd --gid ${GID} $GROUPNAME \
 && useradd --create-home --home-dir /home/$USERNAME --shell /bin/bash --uid ${UID} --gid ${GID} $USERNAME \
 && echo "$USERNAME:$PASSWORD" | chpasswd \
 && chown $USERNAME:$GROUPNAME /home/$USERNAME -R \
 && ulimit -v unlimited

RUN mkdir -p /home/${USERNAME}/.aliaswallet/tor \
 && touch /home/${USERNAME}/.aliaswallet/tor/torrc \
 && chown -R ${USERNAME}:${GROUPNAME} /home/${USERNAME}/.aliaswallet

RUN apt-get update -y \
 && apt-get upgrade -y

RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    mc \
    libboost-chrono1.67.0 \
    libboost-filesystem1.67.0 \
    libboost-program-options1.67.0 \
    libboost-thread1.67.0 \
    libcap2 \
    libevent-2.1-7 \
    libqt5webchannel5 \
    libtool \
    libseccomp2 \
    obfs4proxy \
    qtwebengine5-dev \
    tor \
    wget
